ext/event/backend/uring.c
ext/event/backend/uring.h

Add polling loop when submission queue is full
- Bug fix.

handle full submission queue

---

guides/getting-started/README.md
guides/links.yaml
test/io/event/selector/buffered_io.rb
test/io/event/selector/file_io.rb

Repro and fix https://github.com/socketry/io-event/issues/16
- Bug fix.

Add file io tests and reproduce crash.

---

.github/workflows/development.yml
benchmark/server/buffer.rb
lib/io/event/debug/selector.rb
lib/io/event/selector.rb

Expand the tested Ruby implementations.
- Maintenance.

Expanded Ruby support.

---

ext/io/event/selector/epoll.c

Better logging of error conditions around duplicated file descriptors.
- Bug fix.

Fix duplicate epoll ctl

---

.github/workflows/development.yml

Fix GitHub development workflow.

---

.github/workflows/test.yaml
lib/io/event/debug/selector.rb
lib/io/event/selector.rb
lib/io/event/selector/select.rb
lib/io/event/support.rb
test/io/event/selector.rb
test/io/event/selector/buffered_io.rb
test/io/event/selector/file_io.rb

It would be nice to run the tests / development workflow on Windows.
https://github.com/socketry/io-event/pull/37
- New feature.

Add experimental support for windows to the build matrix.

---

.github/workflows/test-external.yaml
config/external.yaml
ext/io/event/selector/epoll.c
ext/io/event/selector/kqueue.c
ext/io/event/selector/uring.c

Update native extensions for the new interfaces.
- New feature.
- Maintenance.
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
(c) The contribution was provided directly to me by some other
person who certified (a), (b) or (c) and I have not modified
it. …

Update native implementations for new interface.

---

config/external.yaml
ext/extconf.rb

Let's try to get this working on JRuby.
- Bug fix.

Don't try to compile native extension on JRuby.

---

lib/io/event/selector/nonblock.rb
test/io/event/selector/nonblock.rb

Add extra tests for non-windows platforms.
- Bug fix.

Test nonblocking IO on non-windows platforms.

---

ext/extconf.rb
ext/io/event/selector/epoll.c
ext/io/event/selector/selector.h

Native improvements

---

ext/io/event/selector/epoll.c

Fixes <https://github.com/socketry/io-event/issues/57> and <https://github.com/socketry/async/issues/232>.
The implementation falls back to the `epoll_wait` code path if `epoll_pwait2` fails with ENOSYS. We don't cache this... I suppose we could cache it. It won't affect the performance of users on modern kernels but will be a tiny bit slower on older kernels which (1) indicates they support `epoll_pwait2` and (2) don't actually support it. So rather than making the code more complex, please update your kernel.
- Bug fix.

Add fallback to epoll_wait if epoll_pwait2 returns ENOSYS.

---

test/io/event/selector/buffered_io.rb

They usually have bidirectional pipes, which makes the test fail.
- Bug fix.

Skip test on BSD systems.

---

ext/io/event/selector/epoll.c
ext/io/event/selector/kqueue.c
ext/io/event/selector/uring.c

`data` was not clear.
- Maintenance.

Rename `data` -> `selector`.

---

.github/workflows/test-external.yaml
config/external.yaml
ext/io/event/selector/epoll.c
ext/io/event/selector/kqueue.c
ext/io/event/selector/list.h
lib/io/event/selector/select.rb

The external Async test suite was not running correctly - let's rectify that.
- Bug fix.
- Maintenance.

Fix external tests

---

config/external.yaml
ext/io/event/selector/epoll.c
ext/io/event/selector/kqueue.c
ext/io/event/selector/uring.c
lib/io/event/selector/select.rb
test/io/event/selector/interrupt.rb

Add more external tests to stress the code.
- Maintenance.

Add more external tests.

---

.github/workflows/coverage.yaml
lib/io/event/selector.rb
test/io/event/selector.rb
test/io/event/selector/buffered_io.rb

Let's try to get to 100% test coverage.
- Maintenance.

Run coverage tests on more Ruby versions.

---

ext/io/event/selector/uring.c

https://github.com/axboe/liburing/discussions/929
I don't know why, yet, this fixes the issue.
- Bug fix.

Fix a weird bug with duplicate CQEs.

---

.github/workflows/coverage.yaml
.github/workflows/documentation.yaml
.github/workflows/test-external.yaml
.github/workflows/test.yaml
io-event.gemspec
lib/io/event/support.rb
readme.md
test/io/event/selector/cancellable.rb
test/io/event/selector/process_io.rb

Update the CI matrix to support Ruby 3.3.
- Maintenance.

Ruby 3.3 updates

---

.github/workflows/test-external.yaml
.github/workflows/test.yaml
ext/io/event/selector/uring.c

Let's try testing using `io_uring` on Ubuntu as the latest kernel should support it.
- Maintenance.

Add liburing package installation for Ubuntu tests.

---

ext/io/event/selector/selector.h

Add <sys/wait.h> for `WNOHANG`.

---

ext/io/event/selector/epoll.c
ext/io/event/selector/kqueue.c
ext/io/event/selector/uring.c
test/io/event/selector.rb

Give more information about why <https://github.com/socketry/async/issues/317> is failing.
- Debugging.

Include invalid duration in error message.

---

lib/io/event/timers.rb
test/io/event/timers.rb

Rename `Timers::Handle#offset` to `#time` as it's more accurate.

---

ext/io/event/selector/epoll.c
ext/io/event/selector/kqueue.c
ext/io/event/selector/uring.c
lib/io/event/selector/select.rb
test/io/event/selector.rb

Potential fix for <https://github.com/socketry/async/issues/317>
- Bug fix.

Always use `rb_to_float`.

---

.github/workflows/test.yaml
test/io/event/selector.rb
test/io/event/selector/buffered_io.rb
test/io/event/selector/file_io.rb

It would be good if tests were passing on Windows.
- Maintenance.

Let's run tests on windows.

---

ext/io/event/selector/epoll.c

Fix: https://github.com/socketry/io-event/issues/113#issuecomment-2394051652
@ioquatix

Trigger write barriers when setting `IO_Event_Selector_EPoll_Descriptor.io`

---

test/io/event/selector/fifo_io.rb

Add fifo tests.

---

.github/workflows/test-debug.yaml

Let's enable asan and ubsan in our tests.
- Maintenance.

Add debug workflow with sanitizers enabled.

---

ext/io/event/selector/epoll.c

It seems like epoll can sometimes hang on zombie processes: https://github.com/socketry/async/issues/351
We may need to check the process status before waiting.
- Bug fix.

EPoll `process_wait` sometimes hangs on zombie processes.

---

benchmark/server/event.rb
benchmark/server/gems.rb
benchmark/server/scheduler.rb
benchmark/server/thread.rb

Clean up the benchmark code.
- Maintenance.

Cleanup benchmark code.

---

ext/io/event/worker_pool_test.c

This PR should fix https://github.com/socketry/io-event/issues/141
- Bug fix.
- ~~New feature.~~
- ~~Breaking change.~~
- ~~Performance improvement.~~
- ~~Maintenance.~~

Remove unused header file include due to fix build error

---

lib/io/event/priority_heap.rb
releases.md
test/io/event/priority_heap.rb

Introduce `IO::Event::PriorityHeap#delete` and `#delete_if`.
