- .github/workflows/development.yml
* Fixes https://github.com/socketry/event/issues/2
I want to see if CI passes with this.
> Run CI without C exts lock on TruffleRuby

- ext/event/backend/backend.c
- ext/event/backend/backend.h
- ext/event/backend/epoll.c
- ext/event/backend/kqueue.c
- ext/event/backend/pidfd.c
- ext/event/backend/uring.c
- ext/event/extconf.rb
- lib/event/backend/select.rb
- spec/event/selector_examples.rb
This builds on existing work by @dsh0416.
- Implement native `kqueue` `NOTE_EXIT` filter.
- Rework `pidfd` for `epoll` and `uring` to deal with exceptional flow control.
- Notification pipe for `select` implementation.
- New feature.
> Add process wait support.

- ext/event/backend/backend.c
- ext/event/extconf.rb
After discussing it with @eregon, apparently prefixing & should fix the macOS `have_func` from passing.
- Bug fix.
> Prefixing & should avoid checking for the symbol itself.

- ext/event/backend/backend.c
- ext/event/backend/backend.h
- ext/event/backend/epoll.c
- ext/event/backend/kqueue.c
- ext/event/backend/uring.c
- lib/event/backend/select.rb
- spec/event/selector_examples.rb
Provide implementations for `io_read` and `io_write` for all selectors. For `uring`, this is a native code path with fallback to `io_wait` on `EAGAIN`. For all other implementations, it's implemented by using non-blocking I/O in a loop.
- Bug fix.
- New feature.
> General implementation of `io_read` and `io_write`.

- .github/workflows/development.yml
- benchmark/server/buffer.rb
While Async 2.0 is designed for Ruby 3.1, in general this gem might be compatible with older versions of Ruby. Let's check it.
- Maintenance.
> Expanded Ruby support.

- ext/io/event/selector/kqueue.c
Fixes root issue described here:
https://github.com/socketry/async/issues/137
The solution is to set the EV_UDATA_SPECIFIC flag on all kqueue
events, which tells kqueue to consider the udata value (the pointer
to the fiber) as part of the unique tuple.
- Bug fix.
Reprinting the simplified test case from https://github.com/socketry/async/issues/137:
```rb
Async do |t|
puts "Root start"
t.async do
puts "Sleep 1 Start"
sleep 1
puts "Sleep 1 End"
end
t.async do
puts "Sleep 2 Start"
sleep 1
puts "Sleep 2 End"
end
puts "Root end"
end
```
Without this PR, Ruby 3.1.0 prints the following output and hangs:
```
Root start
Sleep 1 StartSleep 2 Start
Root end
Sleep 2 End
```
With this PR on Ruby 3.1.0, the following is output (and doesn't hang):
```
Root start
Sleep 1 StartSleep 2 Start
Root end …
```
> Bugfix: Fix kqueue event clobbering

- ext/io/event/selector/selector.c
- lib/io/event/version.rb
Fix https://github.com/socketry/io-event/issues/24 by pulling in `sys/wait.h`.
- Bug fix.
> Ensure WNOHANG is available on BSD.

- ext/io/event/selector/epoll.c
- test/io/event/selector/file_io.rb
It turns out in some cases `write` can return `EAGAIN` even if it can't be added to epoll. In this case, yield to the event loop.
- Bug fix.
> Yield when waiting on IO would otherwise fail.

- .rspec
- ext/io/event/selector/uring.c
This PR removes unused `.rspec` file and one obsolete line of code in `uring.c`.
- Maintenance.
Existing specs should cover these changes.
> Small cleanup

- config/test.rb
- ext/io/event/selector/epoll.c
- ext/io/event/selector/uring.c
- test/io/event/selector/process_io.rb
`EPOLLHUP` and `POLLHUP` was being silently ignored, which could cause Ruby to hang/fail with EAGAIN in some obscure situations.
- Bug fix.
> Better/correct handling of POLLHUP.

- ext/io/event/selector/epoll.c
- ext/io/event/selector/kqueue.c
- ext/io/event/selector/selector.c
- ext/io/event/selector/uring.c
- fixtures/unix_socket.rb
- lib/io/event.rb
- lib/io/event/selector/nonblock.rb
- lib/io/event/selector/select.rb
- test/io/event/selector.rb
- test/io/event/selector/buffered_io.rb
- test/io/event/selector/nonblock.rb
Since this is needed for Windows to compile, let's implement it and use it if possible.
- Bug fix.
- New feature.
By making a contribution to this project, I certify that:
(a) The contribution was created in whole or in part by me and I
have the right to submit it under the open source license
indicated in the file; or
(b) The contribution is based upon previous work that, to the best
of my knowledge, is covered under an appropriate open source
license and I have the right under that license to submit that
work with modifications, whether created in whole or in part
by me, under the same open source license (unless I am
permitted to submit under a different license), as indicated
in the file; or
(c) The contribution was provided directly to me by some other
person who certified (a), (b) …
> Expose `nonblock` set/restore methods + compatible pure Ruby implementation

- ext/io/event/selector/uring.c
Ensure the io_uring implementation is robust.
- Bug fix.
> Ensure data is always nullified if not otherwise set.

- ext/extconf.rb
Check for `EV_UDATA_SPECIFIC` before building kqueue support which isn't universally supported on systems that support kqueue. See #39 for more details.
- Bug fix.
> Check for `EV_UDATA_SPECIFIC`. Fixes #39.

- test/io/event/selector.rb
- test/io/event/selector/buffered_io.rb
- test/io/event/selector/file_io.rb
Top level `return` is not supported by TruffleRuby.
- Bug fix.
> Don't return early - the tests already check if `io_read` is supported.

- ext/io/event/selector/uring.c
- lib/io/event/selector/select.rb
- test/io/event/selector/buffered_io.rb
While I'm not sure if there were actually sure if there were any real world use cases hitting this, let's do the best effort to clean up if an exception occurs during an asynchronous read or write operation.
- Bug fix.
- New feature.
> Introduce cancellation support for asynchronous `io_read` and `io_write` operations.

- ext/io/event/interrupt.h
Fixes <https://github.com/socketry/io-event/issues/58>.
- Bug fix.
> Fix `IO_Event_Interrupt_descriptor` undefined symbol.

- test/io/event/selector/buffered_io.rb
https://github.com/socketry/async/issues/228
Trying to work around the issue in CRuby which can generate zero length writes.
- Bug fix.
> Add test for zero length write.

- lib/io/event/selector/select.rb
- test/io/event/selector.rb
When multiple fibers wait on different events for the same IO object and only a subset of the polled events happen, some of the fibers could be woken up prematurely (with a subset of the events they asked for) and dropped from the queue.
Fix by re-inserting the waiters into the IO object's queue when none of their events were triggered.
- Bug fix.
I tried to modify the existing code as little as possible to fix this, but it's really starting to make the per-IO queue handling way more complicated than it should be...
> Fix Select selector backend per-IO waiter queue handling

- ext/extconf.rb
- ext/io/event/selector/array.h
- ext/io/event/selector/epoll.c
- ext/io/event/selector/kqueue.c
- ext/io/event/selector/list.h
- ext/io/event/selector/selector.h
- ext/io/event/selector/uring.c
- lib/io/event/selector/select.rb
- test/io/event/selector.rb
- test/io/event/selector/buffered_io.rb
As discussed in <https://github.com/socketry/io-event/issues/65>, it's possible for the list of events in `IO_Event_Selector_EPoll_select` to contain cancelled operations. If during cancellation, another operation is scheduled, a spurious wakeup can be generated. Adding one layer of indirection, in the form of cancelled tokens, avoids this situation, since each operation has a unique token which can independently be cancelled.
The overhead of this is extra memory allocations, but these can be pooled. We could compare the cost of `malloc`. There may be little point pooling these tokens.
Fixes #65.
- Bug fix.
> Spurious wakeups

- ext/io/event/selector/epoll.c
- test/io/event/selector.rb
> Don't use EPOLLONESHOT for the wakeup event.

- test/io/event/selector.rb
- Failing test case.
I think I found another problem. Probably related to the "lazy disarming" optimization.
IIUC, the selector can mistakenly assume that events for a certain FD are already being polled, but they aren't because the FD has been closed and reopened since last time.
The test case works if you comment out `local.close`.
I think it's triggering some other problem I was investigating, but not sure...
> Failing test case for waiting on a reused FD.

- ext/io/event/selector/epoll.c
- ext/io/event/selector/kqueue.c
<https://github.com/socketry/io-event/pull/69> introduced a failing test case.
File descriptors may be reused. Caching based on descriptor can therefore cause missing registrations.
- Bug fix.
> Always re-register epoll descriptor.

- ext/io/event/selector/array.h
- ext/io/event/selector/epoll.c
- ext/io/event/selector/kqueue.c
- ext/io/event/selector/list.h
- ext/io/event/selector/selector.h
- ext/io/event/selector/uring.c
Fix our garbage collection and add support for compacting GC.
This also ensures that all fibers are retained if they are waiting in the event loop, a departure from existing behaviour (probably for the better).
cc @nevans
See also: https://bugs.ruby-lang.org/issues/18818
- Bug fix.
- New feature.
> Introduce correct support for compacting GC.

- ext/io/event/selector/epoll.c
- ext/io/event/selector/kqueue.c
- ext/io/event/selector/selector.c
- ext/io/event/selector/selector.h
- ext/io/event/selector/uring.c
`rb_process_status_wait` is not exposed yet in CRuby, but when/if it is, it will take a flags argument.
`WNOHANG` should always be set, as it's used to (efficiently) by-pass the fiber scheduler.
- Bug fix.
- New feature.
- Maintenance.
> Correctly pass through flags `rb_process_status_wait`.

- ext/io/event/selector/epoll.c
- ext/io/event/selector/kqueue.c
- ext/io/event/selector/list.h
Fixes https://github.com/socketry/io-event/issues/83.
- Bug fix.
> Ensure that the saved node is freed correctly if an exception occurs.

- .github/workflows/test.yaml
- ext/io/event/event.h
- ext/io/event/interrupt.h
- ext/io/event/selector/array.h
- ext/io/event/selector/epoll.c
- ext/io/event/selector/list.h
- ext/io/event/selector/pidfd.c
* Fixes https://github.com/socketry/io-event/issues/88,
the issue explains it in details.
* `#include "extconf.h"` is redundant and a code smell for missing ruby.h,
ruby/internal/config.h already does `#include RUBY_EXTCONF_H`.
- Bug fix.
> Always #include <ruby.h> before any system header

- lib/io/event/version.rb
- test/io/event/selector/fifo_io.rb
> Add fifo tests.

- guides/getting-started/readme.md
- lib/io/event/debug/selector.rb
- lib/io/event/selector.rb
Add log support to the debug selector.
- New feature.
> Add support for logging operations to debug selector.

- bake.rb
- ext/io/event/selector/selector.h
fixes a compile error on mingw
```
compiling ./io/event/event.c
In file included from ./io/event/event.c:22:
./io/event/selector/selector.h:37:10: fatal error: sys/wait.h: No such file or directory
37 | #include <sys/wait.h>
```
which has been broken by a recent change https://github.com/socketry/io-event/pull/94
also, Windows tests weren't running properly on GHA
- Bug fix.
> fix mingw build

- ext/io/event/selector/epoll.c
- ext/io/event/selector/kqueue.c
- ext/io/event/selector/uring.c
- lib/io/event/debug/selector.rb
- lib/io/event/selector/select.rb
- test/io/event/selector.rb
Expose the `idle_duration` so that we can compute load metrics.
This feature should be considered experimental and may be changed/removed in the future.
- New feature.
> Expose `#idle_duration` - for experimental load calculation.

- ext/io/event/selector/kqueue.c
- test/io/event/selector.rb
Not sure how this was compiling but it was.
```
./io/event/selector/kqueue.c:374:2: warning: incompatible pointer types assigning to 'struct IO_Event_Selector_KQueue *' from 'struct IO_Event_Selector_EPoll *' [-Wincompatible-pointer-types]
TypedData_Get_Struct(self, struct IO_Event_Selector_EPoll, &IO_Event_Selector_KQueue_Type, selector);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/samuel/.rubies/ruby-3.3.0/include/ruby-3.3.0/ruby/internal/core/rtypeddata.h:516:13: note: expanded from macro 'TypedData_Get_Struct'
((sval) = RBIMPL_CAST((type *)rb_check_typeddata((obj), (data_type))))
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
- Bug fix.
> Fix `IO_Event_Selector_EPoll` -> `KQueue` typo.

- .contributors.yaml
- io-event.gemspec
- lib/io/event.rb
- lib/io/event/priority_heap.rb
- lib/io/event/timers.rb
- license.md
- test/io/event/priority_heap.rb
- test/io/event/timers.rb
I'd like to expose a native implementation of this for performance reasons. Additionally, we might expose some higher level constructs in the selector, for scheduling timers.
- New feature.
> Add priority heap and timers implementation (reworked from timers gem).

- ext/io/event/selector/epoll.c
- ext/io/event/selector/kqueue.c
- ext/io/event/selector/uring.c
One reason <https://github.com/socketry/async/issues/317> might be failing is because we are not handling bignums. Let's fix that.
- Bug fix.
> Support conversion of T_BIGNUM.

- ext/extconf.rb
- ext/io/event/selector/selector.h
Potential fix for <https://github.com/socketry/io-event/issues/99> and <https://github.com/socketry/io-event/issues/98>.
- Maintenance.
> Explicitly pull in `<sys/wait.h>` for WNOHANG.

- lib/io/event/selector/select.rb
- lib/io/event/timers.rb
- test/io/event/timers.rb
Ensure timer offset is converted to a floating point value.
Fixes <https://github.com/socketry/async/issues/317>.
- Bug fix.
> `Timers#after` converts argument to float.

- lib/io/event/selector/select.rb
- test/io/event/selector.rb
Because the idle duration was not set to zero in some cases, it could create a negative load calculation:
```
@busy_time: 0.0 @idle_time: 0.0 total_time: 0.0
@busy_time: 0.00042687399999863374 @idle_time: 0.0 total_time: 0.00042687399999863374
@busy_time: 0.00048479200000883793 @idle_time: 0.0 total_time: 0.00048479200000883793
@busy_time: 0.0005139570000096683 @idle_time: 0.0 total_time: 0.0005139570000096683
@busy_time: 0.0005577590000029886 @idle_time: 0.010063733000009734 total_time: 0.010621492000012722
@busy_time: 0.0006385590000093089 @idle_time: 0.03013504500000863 total_time: 0.03077360400001794
@busy_time: -0.01935752299996807 @idle_time: 0.05020635700000753 total_time: 0.03084883400003946
@busy_time: -0.03933384799998407 @idle_time: 0.07027766900000643 total_time: …
```
> Fix idle load computation.

- ext/io/event/interrupt.c
Since Ruby 3.2, `pipe` function declaration is provided in https://github.com/ruby/ruby/blob/21c708ee802e1a59901eccc6448e40e8f72189b8/include/ruby/missing.h#L292
However, it does not provided it with Ruby 3.1.
This patch will define `pipe` macro to use proper function due to fix build error.
- Bug fix.
Fix https://github.com/socketry/io-event/issues/111
> Fix build error with Ruby 3.1 on Windows

- ext/io/event/event.c
- ext/io/event/selector/epoll.c
- ext/io/event/selector/kqueue.c
- ext/io/event/selector/uring.c
These global variables aren't used anywhere, might as well not expose them, and not need to register them.
But even then, registering them wasn't really necessary because classes defined from C API are pinned and immortal.
> Dont expose global references needlessly

- ext/io/event/selector/list.h
- ext/io/event/selector/uring.c
Not a big deal at all, but I noticed this while auditing write barriers, figured I'd fix it.
> Include free list size in URing memsize

- ext/io/event/selector/selector.c
This is nitpick territory, but when I'm auditing a C extension for write barrier issues, what I do is that I go over all the `VALUE` fields in strucs and for each for them I grep for `->field = `.
This makes it quick to ensure all places where the value is assigned do trigger a write barrier.
With this workflow, `RB_OBJ_WRITTEN` end up causing false positive.
> Prefer `RB_OBJ_WRITE` over `RB_OBJ_WRITTEN`

- lib/io/event/support.rb
When https://github.com/ruby/ruby/pull/11777 is merged, we can relax the limitation on support for `IO::Buffer`.
- Maintenance.
> Restore support for `IO::Buffer` in Ruby v3.2.6.

- ext/io/event/selector/epoll.c
- ext/io/event/selector/kqueue.c
- ext/io/event/selector/uring.c
- test/io/event/selector/allocation.rb
Fixes <https://github.com/socketry/io-event/issues/121>
- Bug fix.
> Add waiting fiber write barrier for all selector implementations.

- ext/io/event/selector/selector.c
Possible fix for <https://github.com/socketry/io-event/issues/123>.
Even thought there is a pointer on the stack, it's a pointer to itself (`rb_fiber_current`) and thus a circular reference, thus entirely possible for the GC to clean up this fiber.
- Bug fix.
> Add write barriers to `IO_Event_Selector_resume/_raise`.

- ext/io/event/selector/epoll.c
- ext/io/event/selector/kqueue.c
- ext/io/event/selector/uring.c
- releases.md
While `io_uring`, `epoll`, and `kqueue` may be available at compile time, their actual support at runtime is not guaranteed. Various factors, such as kernel configuration, security policies (seccomp, AppArmor, SELinux), or resource limits, may prevent them from working as expected.
This PR introduces explicit runtime checks for each event selector, ensuring that we only define the corresponding constant when the selector is truly available. 
While it would be possible to defer these checks until selector creation, this approach follows the existing pattern of defining constants at initialization time, keeping the implementation consistent with the current interface.
- Adds `IO_Event_Selector_URing_supported_p()`, `IO_Event_Selector_EPoll_supported_p()`, and …
> Validate selector support at run time.

- ext/extconf.rb
Linux system with latest GCC 15 can't compile this gem. See more #136
Use append_cflags instead of modifying CFLAGS directly 
According to this thread
https://inbox.vuxu.org/ruby-core/redmine.issue-21290.20250428190637.58020@ruby-lang.org/T/
`ed25519` gem had a [similar issue](https://github.com/RubyCrypto/ed25519/issues/44), and it was resolved by migrating to append_cflags.
https://github.com/RubyCrypto/ed25519/commit/c1ee0e0cd5807048d2382feba3d6ad8aad850b0c
Let's move this gem to append_cflags as well. This approach is recommended over modifying CFLAGS since it ensures compatibility across different build environments by checking whether the flag is acceptable, and should not affect most systems. 
In the meantime, it appears that Nobu has merged a wider fix to ruby itself. But this …
> Use append_cflags instead of modifying CFLAGS directly
